---
driver:
  name: ec2
  region: ca-central-1
  subnet_id: subnet-99e681e2
  security_group_ids: 
    - sg-24901f4c
  aws_ssh_key_id: testkitchen
  instance_type: t2.xlarge

transport:
  ssh_key: C:\amaz\testkitchen.pem
  connection_timeout: 10
  connection_retries: 5

platforms:
- name: ubuntu-16.04
  driver:
    image_id: ami-018b3065
  transport:
    username: ubuntu
- name: ubuntu-17.10
  driver:
    image_id: ami-cfba02ab
  transport:
    username: ubuntu
- name: ubuntu-17.04
  driver:
    image_id: ami-02b20966
  transport:
    username: ubuntu
- name: debian-9.3
  driver:
    image_id: ami-1545ff71
  transport:
    username: admin
- name: centos-7.4
  driver:
    image_id: ami-b111aad5
  transport:
    username: centos

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  #the default setting:
  #playbook: default.yml
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false
  #ansible_connection: winrm
  #require_windows_support: true
  #extra_vars:
  #  vnc_desktop: gnome
  #  vnc_server: tigervnc

suites:
 - name: default
 