---
- name: reboot message
  debug:
    msg:
    - "***********************"
    - " "
    - "You should reboot this server {{ inventory_hostname }}, as a one-time action, if it hasn't ever been rebooted."
    - " "
    - "***********************"
  when:
    - vnc_reboot_once is not defined or vnc_reboot_once == False

- name: reboot once
  shell: reboot
  args:
    chdir: /
  when:
    - vnc_reboot_once is defined and vnc_reboot_once == True
